# Just an example how to check and upgrade the sonoff-tasmota from the Home Assistant
# Twitter link: https://goo.gl/e3y7pa
# 
# 1. Open your sonoff webinterface and add in the "Firmware Upgrade" menu following OTA Url, save! Example: https://goo.gl/6ZMjzA
# OTA Url: http://sonoff.maddox.co.uk/tasmota/sonoff.bin
#
# 2. Below the Home Assistant configuration:
# homeassistant:
script:   
  check_sonoffs_version:
      sequence:
        - service: mqtt.publish
          data_template:
            topic: "cmnd/sonoffs/status"
            payload: 2

  # update_sonoffs: 
  #     sequence:
  #       - service: mqtt.publish
  #         data_template:
  #           topic: "cmnd/sonoffs/upgrade"
  #           payload: 1
            
sensor:  
  - platform: rest
    name: Sonoff latest release
    resource: https://api.github.com/repos/arendst/Sonoff-Tasmota/releases/latest
    value_template: '{{ value_json.tag_name }}'
    headers:
      Accept: application/vnd.github.v3+json
      Content-Type: application/json
      User-Agent: Home Assistant REST sensor 
  - platform: mqtt
    name: Sonoff POW Boiler Version
    state_topic: "stat/sonoff1/STATUS2"
    value_template: "{{ value_json['StatusFWR'].Version }}"
  - platform: mqtt
    name: Sonoff POW HomeCCTV Version
    state_topic: "stat/sonoff2/STATUS2"
    value_template: "{{ value_json['StatusFWR'].Version }}"
  - platform: mqtt
    name: Sonoff Touch Kitchen Version
    state_topic: "stat/sonoff3/STATUS2"
    value_template: "{{ value_json['StatusFWR'].Version }}"
  - platform: mqtt
    name: Sonoff HallWay Light Version
    state_topic: "stat/sonoff4/STATUS2"
    value_template: "{{ value_json['StatusFWR'].Version }}"
  - platform: mqtt
    name: Sonoff XiaomiCCTV Version
    state_topic: "stat/sonoff5/STATUS2"
    value_template: "{{ value_json['StatusFWR'].Version }}"