homeassistant:
  customize_glob: !include config/customize_glob.yaml
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret HomeLatitude
  longitude: !secret HomeLongitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 0
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Asia/Jerusalem
  # Customization file
  customize: !include config/customize.yaml
  packages: !include_dir_named config/packages
  whitelist_external_dirs:
    - /config # - /home/homeassistant/.homeassistant/
    - /config/tmp # - /home/homeassistant/.homeassistant/tmp
    - /config/backup/hass #- /home/homeassistant/backup/hass

# custom_ui
customizer:
  custom_ui: hosted

# Enables the frontend

frontend:
  javascript_version: latest #auto
  themes: !include config/themes.yaml
  # extra_html_url:
  #   - /local/custom_ui/state-card-custom-ui.html
  #   - /local/custom_ui/state-card-floorplan.html
  # extra_html_url_es5:
  #   - /local/custom_ui/state-card-custom-ui-es5.html
  # extra_html_url: #???
  # - /local/custom_ui/custom-weather-card.html

recorder:
  purge_keep_days: 7
  # db_url: mysql://hassuser:<Eliran007>@localhost/hass_db?charset=utf8
  # db_url: mysql://hassuser:Eliran007@localhost/hass_db
  
http:
  # Secrets are defined in the file secrets.yaml
  api_password: !secret api_password
  # ssl_certificate: !secret ssl_certificatePATH
  # ssl_key: !secret ssl_keyPATH 
  base_url: !secret base_url
  ip_ban_enabled: True
  login_attempts_threshold: 5
  use_x_forwarded_for: True
  trusted_proxies:
    - 127.0.0.1 #localhost
    - 192.168.1.1 #router
    - 172.18.0.2 #nginx
    - 172.18.0.3 #nginx

#DD-WRT
device_tracker:
  - platform: asuswrt
    host: 192.168.1.1
    username: !secret AsusWrtUsername
    password: !secret AsusWrtPassword
    interval_seconds: 10
    track_new_devices: yes
    consider_home: 90 

#Xiaomi Gateway (Aqara)
xiaomi_aqara:
  discovery_retry: 10
  gateways:
    - key: !secret XiaomiGatewayKey
 
vacuum:
  - platform: xiaomi_miio
    name: Xiaomi Vacuum
    host: 192.168.1.82
    token: !secret XiaomiVacuumV1Token
    
cast:
  media_player:
  - host: 192.168.1.104 #partnerTV
  
apple_tv:
  - host: 192.168.1.121
    name: Apple TV
    login_id: !secret AppleTVLogin_id
    credentials: !secret AppleTVcredentials

timer:
  #a Timer that Start Every time that the Home Door Open 
  dogwalk:
    duration: '00:30:00'
    icon: mdi:paw

#for iftt api via webhook (using with webhook for sonoff etc... )
# ifttt:
#   key: !secret Iftt_key

mqtt:
  password: !secret mqtt_password
  
# Enables configuration UI
config:

#for HA Update Available Notification
updater:

discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
# conversation:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

weather:
  #For the Custom-UI-Weather-state-card
  - platform: yweather

# Text to speech
tts:
  - platform: google #english 

cloudflare:
  email: !secret MyEmail 
  api_key: !secret CloudflareAPIKey
  zone: !secret CloudflareZone
  records:
    - !secret CloudflareSubDomain1

# Cloud
cloud:

binary_sensor:
  - platform: mqtt #floorPlan
    state_topic: dummy/floorplan/sensor
    name: Floorplan
    
panel_custom:
  - name: floorplan
    sidebar_title: Floorplan
    sidebar_icon: mdi:home
    url_path: floorplan
    config: !include config/floorplan.yaml
    
# https://www.home-assistant.io/components/notify.telegram/
telegram_bot:
  - platform: polling
    api_key: !secret TelegramBotApiKey
    allowed_chat_ids:
      - !secret TelegramChatIDNum1 
      
custom_updater:
  track:
    - components
    - cards
    - python_scripts
  card_urls:
      - https://raw.githubusercontent.com/rdehuyss/homeassistant-lovelace-google-calendar-card/master/custom_updater.json
      - https://raw.githubusercontent.com/rdehuyss/homeassistant-lovelace-alarm-clock-card/master/custom_updater.json
      - https://raw.githubusercontent.com/bramkragten/custom-ui/master/updater.json
climate:
  - platform: sensibo
    api_key: !secret SensiboApiKey
#https://www.home-assistant.io/components/logger/
logger:
  default: warning #error #warning #info #warning #degbug

google:
  client_id: !secret Google_CLIENT_ID
  client_secret: !secret Google_CLIENT_SECRET
  
# zoneminder:
#   host: 192.168.1.200:8081  

##############
## includes
############
sensor: !include config/sensors.yaml
group: !include config/groups.yaml #groups at External FILE
automation: !include_dir_merge_list config/automation/
script: !include config/scripts.yaml
input_select: !include config/input_select.yaml
input_boolean: !include config/input_boolean.yaml
input_number: !include config/input_number.yaml
camera: !include config/cameras.yaml
switch: !include config/switchs.yaml  
remote: !include config/remotes.yaml  
light: !include config/lights.yaml  
ios: !include config/ios.yaml
notify: !include config/notify.yaml
weblink: !include config/weblink.yaml
panel_iframe: !include config/panel_iframe.yaml
zone: !include config/zones.yaml
history: !include config/history.yaml
shell_command: !include config/shell_commands.yaml
intent_script: !include config/intent_scripts.yaml
logbook: !include config/logbook.yaml # View all events in a logbook
homekit: !include config/homekit.yaml # For apple HomeKit support
#alexa support Via Haaska (v3)
#to avoid from monthly payments (in Home Assitant Cloud) 
#and to give more options for customization
alexa: !include config/alexa.yaml
#Currently, not in use !
#google_assistant: !include config/google_assistant.yaml 

############################################################################
##
## sonoff1 = sonoff pow boiler ( switch._mqtt_pow1 )
## sonoff2 = sonoff pow 2 general - now for homeCCTV Kitchen( switch.mqtt_pow2 )
## sonoff3 = sonoff touch - now for Kitchen Light ( light.sonoff_light )
## sonoff4 = sonoff basic -now for Hallway Light (light.sonoff_hallway_light )
## sonoff5 = sonoff basic - now for Xiaomi CCTV ( switch.sonoff_xiaomicctv_switch )
##
############################################################################