################################################################################
#
#CAMERA
#
################################################################################
- platform: onvif
  name: Home CCTV1
  host: !secret HomeCCTV1IP
  port: 10080
  username: !secret HomeCCTV1username
  password: !secret HomeCCTV1password
  
- platform: ffmpeg
  name: Home CCTV2
  input: !secret HomeCCTV2URL
  
# - platform: onvif
#   name: Outdoor CCTV
#   host: !secret OutdoorCCTVIP
#   port: 10080
#   username: !secret OutdoorCCTVusername
#   password: !secret OutdoorCCTVpassword
  
- platform: ffmpeg
  name: Outdoor CCTV
  input: !secret OutdoorCCTV_02_URL
  
- platform: local_file #for security warnings 
  file_path: '/config/tmp/home_cctv1.png'
  name: "CCTV1_Snapshot"
  

# - platform: zoneminder