# camera:
- platform: onvif
  name: Home CCTV1
  host: 192.168.1.103
  port: 10080
  username: !secret HomeCCTV1username
  password: !secret HomeCCTV1password

- platform: onvif
  name: Outdoor CCTV
  host: 192.168.1.114
  port: 10080
  username: !secret OutdoorCCTVusername
  password: !secret OutdoorCCTVpassword
  
# - platform: onvif
#   name: Home CCTV2
#   host: 192.168.1.67
#   username: !secret CCTV2Username
#   password: !secret CCTV2Pass

- platform: generic
  name: Home CCTV2
  still_image_url: HomeCCTV2URL #http://USER:PASS@CAMERA_IP/ISAPI/Streaming/channels/102/picture
  framerate: 30

- platform: local_file #for security warnings 
  file_path: 'tmp/home_cctv1.png'
  name: "CCTV1_Snapshot"

