##################################################
#
# GOOGLE ASSISTANT - The Manual Way no Monthly Payment.
# https://www.home-assistant.io/components/google_assistant/#first-time-setup
#
##################################################
  
  project_id: !secret Google_Home_project_id
  api_key: !secret Google_Home_API_KEY
  exposed_domains:
    - light
    - switch
    - vacuum
    - script
    #- climate
    - media_player
    
  entity_config:
########################################
###LIGHTS
########################################
    light.white_bulb:
      name: Left Bulb
      room: Salon

    light.living_room_color_bulb:
      name: Right Bulb
      room: Salon

    light.sonoff_light:
      name: Kitchen
      room: Kitchen
      aliases:
        - Kitchen light

    light.philips_bulb:
      name: Service
      room: Service
      aliases:
        - Service light
        - Philips light
    light.sonoff_hallway_light:
      name: Misdaron
      room: Hallway
      aliases:
        - Hallway
        - MISSDARON
        - MISSDARON light
    light.gateway_light_34ce0088d2f7:
      name: Gateway
      room: Salon
      aliases:
        - GateWay light
        
    light.desk_lamp:
      name: Desk Lamp
      room: Bedroom
      aliases:
        - Desk Lamp
        - Bedroom Light
###############expose: FALSE##################
    light.yeelight_rgb_286c07106e1b:
      expose: false
    light.yeelight_white_f0b4290e4e68:
      expose: false    
########################################
###SWITCHS
########################################
    switch.mqtt_pow2:
      name: Kitchen Camera
      room: Kitchen
      
    switch.sonoff_xiaomicctv_switch:
      name: Salon Camera
      room: Salon
      
    switch.tv_lg:
      name: TV
      room: Salon
      
    switch.tv_lg_vol:
      name: Volume
      room: Salon
      aliases:
        - Volume TV
        - TV Volume
    switch.tv_lg_mute:
      name: Mute
      room: Salon
      aliases:
        - Mute TV
        - TV Mute
        
    switch._mqtt_pow1:
      name: Boiler
      room: Hallway
      
    switch.xiaomi_powerstrip:
      name: Power strip
      room: Salon
###############expose: FALSE##################
    switch.tv_lg_hdmi1:
      expose: false
    switch.tv_lg_hdmi2:
      expose: false
    switch.tv_lg_hdmi3:
      expose: false    
########################################
###Vaccum
########################################      
    vacuum.xiaomi_vacuum:
      name: Vaccum Cleaner
      room: Hallway
      aliases:
        - Roobik
        
########################################
###SCRIPTS
########################################
    script.restart_home_assistant:
      name: Restart Home Assitant
      room: Garage
    script.reboot_router:
      name: Reboot Router
      room: Garage
    script.backup_ha_and_move_backup_to_unraid:
      name: Backup Home Assitant
      room: Garage
###############expose: FALSE##################
    script.backup_ha_config:
      expose: false    
    script.check_sonoffs_tasmota_status:
      expose: false    
    script.update_hass:
      expose: false
    script.timer_off_boiler:
      expose: false
    script.ilradio:
      expose: false
    script.check_sonoffs_version:
      expose: false
    script.backup_all_os:
      expose: false
    script.test_push:
      expose: false
    script.white_night_light:
      expose: false
    script.purple_night_light:
      expose: false
    script.flash_gateway1:
      expose: false
    script.flash_gateway2:
      expose: false
    script.install_after_update_hass:
      expose: false
    script.update_speedtestnet:
      expose: false 
    script.morning_sequence:
      expose: false 
      
########################################
###CLIMATE- not in use - Sensibo API better
########################################      
#     climate.living_room:
#       name: AC
#       room: Salon
#       aliases:
#         - MAZGAN
#         - Air con
#         - Air conditioning
#         - Air conditioner
########################################
###MEDIA PLAYER
########################################      
    media_player.apple_tv:
      name: Apple TV
      room: Salon
    media_player.partnertv:
      name: Partner TV
      room: Salon      
########################################
###GENERAL
########################################      
    binary_sensor.motion_sensor_158d0000e62376:
      name: Hallway motion
      expose: true
