################################################################################
#
#INPUT BOOLEAN
#
################################################################################
  alarm_clock_status:
    initial: off

  boiler_on_clock_status:
    initial: off
  boiler_off_clock_status:
    initial: off
    
  ac_status_alexa:
    initial: off
#For the Custom-UI-Weather-state-card
  weather:
    name: מזג אוויר