  #a button to restart HA 
  restart_home_assistant:
    alias: Restart Home Assistant
    sequence:
      - alias: Restart Home Assistant
        service: homeassistant.restart
  #just to test if the push working
  test_push:
    alias: 'test_push'
    sequence:
      - service: notify.ios_eliran_iphone
        data:
          message: 'This is a test!'
          data:
            attachment: 
              url: https://67.media.tumblr.com/ab04c028a5244377a0ab96e73915e584/tumblr_nfn3ztLjxk1tq4of6o1_400.gif

###########################################
  timer_off_boiler: #script to turn off the boiler after X mins that been choose before
    alias: הדלק טיימר דוד
    sequence:
      - delay: '00:{{ states.input_number.slider_boiler.state | int }}:00'
      - service: switch.turn_off
        data:
          entity_id: switch._mqtt_pow1

###########################################
  update_hass:
     alias: 'Update HASS and restart' #Update Hass and Restart HA
     sequence:
       - service: shell_command.hassbian_ha_update
       - service: homeassistant.restart
###############################################
  reboot_os:
     alias: 'Restart the Raspberry PI'
     sequence:
       - service: shell_command.os_reboot
###############################################
  backup_all_os:
     alias: 'Backup RPI To USB'
     sequence:
       - service: shell_command.backup_all_rpi_to_usb
###############################################
  backup_ha_config:
     alias: 'Backup Home Assitant config'
     sequence:
       - service: shell_command.backup_hass_config
###############################################
  #a button to make speed test 
  update_speedtestnet:
    alias: Update SpeedtestNet info
    sequence:
      - service: sensor.update_speedtest
############################################### 
  white_night_light:
    alias: White
    sequence:
      - service: homeassistant.turn_on
        entity_id: light.gateway_light_34ce0088d2f7
        data:
          brightness: 255
          rgb_color: [255,255,255]

  purple_night_light:
    alias: Purple
    sequence:
      - service: homeassistant.turn_on
        entity_id: light.gateway_light_34ce0088d2f7
        data:
          brightness: 255
          rgb_color: [88,0,82]

  flash_gateway1:
    alias: Flash Gateway On
    sequence:
      - service: light.turn_on
        data:
          entity_id: light.gateway_light_34ce0091234
          color_name: red
          brightness: 255
      - delay:
          # supports seconds, milliseconds, minutes, hours
          milliseconds: 600
      - service: script.turn_on
        data:
          entity_id: script.flash_gateway2

  flash_gateway2:
    alias: Flash Gateway OnV2
    sequence:
      - service: light.turn_off
        data:
          entity_id: light.gateway_light_34ce0091234

      - service: script.turn_on
        data:
          entity_id: script.flash_gateway1
#for Xiaomi IR
  turn_on_tv:
    sequence:
      - service: remote.send_command
        entity_id: 'remote.ir_controller'
        data:
          command:
            - 'turn_on_tv'
  turn_off_tv:
    sequence:
      - service: remote.send_command
        entity_id: 'remote.ir_controller'
        data:
          command:
            - 'turn_off_tv'
  tv_input:
      sequence:
        - service: remote.send_command
          entity_id: 'remote.ir_controller'
          data:
            command:
              - 'tv_input'
  tv_vol_up:
      sequence:
        - service: remote.send_command
          entity_id: 'remote.ir_controller'
          data:
            command:
              - 'tv_vol_up'
  tv_vol_down:
      sequence:
        - service: remote.send_command
          entity_id: 'remote.ir_controller'
          data:
            command:
              - 'tv_vol_down'
              
              
  ac_turn_on:
      sequence:
        - service: remote.send_command
          entity_id: 'remote.ir_controller'
          data:
            command:
              - 'ac_turn_on'
  ac_turn_off:
      sequence:
        - service: remote.send_command
          entity_id: 'remote.ir_controller'
          data:
            command: 
              - 'ac_turn_off'       
  ac_fan_speed:
      sequence:
        - service: remote.send_command
          entity_id: 'remote.ir_controller'
          data:
            command: 
              - 'ac_fan_speed'               
############

  test_actionable_notify:
    alias: 'Test light off Notification'
    sequence:
      - service: notify.ios_eliran_iphone
        data:
          message:  'Kitchen lights are still on!'
          data:
            push:
              badge: 0
              category: "homelights"
            action_data:
              entity_id: group.AllMylightsxf

#### need to be tested if working 100% ####
  morning_sequence:
    sequence:
      - service: media_player.volume_set
        data:
          entity_id: media_player.apple_tv
          volume_level: 0.3
      - service: tts.google_say
        data_template:
          # entity_id: media_player.kitchen_audio
          entity_id: media_player.apple_tv
          message: "Good morning!. בוקר טוב"
          # The time is {{ states.sensor.time.state }} and it's {{ states.sensor.date.state}}. Today the weather is {{ states.sensor.dark_sky_hourly_summary.state }}. There is a {{states.sensor.dark_sky_precip_probability.state | round(0) }} percent chance of {{states.sensor.dark_sky_precip.state}} today with an intensity of {{ states.sensor.dark_sky_precip_intensity.state | round(0) }} millimeters. The Temperature is {{ states.sensor.dark_sky_temperature.state | round(0) }} degrees but it will feel like {{ states.sensor.dark_sky_apparent_temperature.state | round(0) }}. The wind speed is {{ states.sensor.dark_sky_wind_speed.state | round(0) }} meters per second."
  ilradio:
    alias: Play Radio on Chromecast Audio
    sequence:
      - service: media_player.volume_set
        data:
           entity_id: media_player.apple_tv
           volume_level: '0.50'
      -  service: media_player.play_media
         data_template:
           entity_id: >
            {% if is_state("input_select.chromecast_radio", "Livingroom") %} media_player.apple_tv
            {% endif %}
           media_content_id: >
            {% if is_state("input_select.radio_station", "GalGalatz") %} http://player.gl.bynetcdn.com/Redirector/glz/glglz/ICE-live
            {% elif is_state("input_select.radio_station", "Galatz") %} http://player.gl.bynetcdn.com/Redirector/glz/glz/ICE-live
            {% elif is_state("input_select.radio_station", "Radius 100FM") %} http://100fm.streamgates.net/Radios100Fm
            {% elif is_state("input_select.radio_station", "Echo 99FM") %} http://99.livecdn.biz/99fm_aac
            {% elif is_state("input_select.radio_station", "Kan 88FM") %} http://radiocast-rr-d.vidnt.com/ipbc_IPBC88LAM
            {% elif is_state("input_select.radio_station", "103FM") %} http://103fm.live.streamgates.net/103fm_live/1multix/icecast.audio
            {% elif is_state("input_select.radio_station", "Lev Hamedina 91FM") %} http://gb92.multix-technologies.com/Lev91Fm
            {% elif is_state("input_select.radio_station", "Reshet Gimel") %} http://radiocast-rr-d.vidnt.com/ipbc_IPBCgimmelLAM
            {% elif is_state("input_select.radio_station", "Radio Darom") %} http://audio-darom.ecast.co.il:9000/darom97fm
            {% elif is_state("input_select.radio_station", "Kol Hayam Haadom 102FM") %} http://eilat.cdnwz.net/102fm
            {% endif %}
           media_content_type: 'audio/mp4'