################################################################################
#
#WEBLINK
#
#################################################################################
  entities:
    - name: SpeedTest 018
      url: http://018.speedtestcustom.com
      icon: mdi:speedometer
      
    - name: My Super Led RGB
      url: https://gamadril.github.io/hyperion-remote
      icon: mdi:led-strip

    - name: IDE
      icon: mdi:cloud-braces
      url: !secret c9IdeURL
      
    - name: Router
      icon: mdi:router-wireless
      url: !secret RouterURL
      
    - name: Server
      icon: mdi:desktop-classic
      url: !secret serverURL
      
    - name: NextCloud
      icon: mdi:cloud-download
      url: !secret NextCloudURL
      
    - name: CloudFlare
      icon: mdi:cloud-sync
      url: !secret cloudflareURL
      
